name: "JetBrains Bug Report ፨"
description: "Anything related to JetBrains IDEs: IntelliJ, Goland, WebStorm, etc."
labels:
  - team/jetbrains
projects:
  - sourcegraph/381

body:
  - type: textarea
    id: installation_information
    attributes:
      label: "Installation Information:"
      value: |
        <!-- Trigger the action "About", click on "Copy and close" and paste the output here -->
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "(optional) Error message or idea.log output:"
      value: |
        <!-- Trigger the action "Show Log", open the file, search for exceptions related to Cody/Sourcegraph and copy relevant lines here -->
        <!-- Alternatively, feel free to upload idea.log as an attachment but please make sure it doesn't contain sensitive information (it normally doesn't) -->
    validations:
      required: false
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to reproduce:"
      value: |
        <!-- Explain what you did to reproduce the problematic behavior -->
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behaviour:"
      value: |
        <!-- Explain how you expected the plugin to behave instead -->
    validations:
      required: true
