name: Build with Cody
on:
  workflow_dispatch:
    inputs:
      cody-commit:
        description: 'Cody commit to build the plugin with (latest by default)'
        required: false
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      # See note about QEMU and binfmt requirement here https://github.com/vercel/pkg#targets
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3
      - run: yarn global add pnpm@8.6.7
      - run: |
          echo "LATEST_COMMIT=$(git ls-remote https://github.com/sourcegraph/cody refs/heads/main | cut -f1)" >> $GITHUB_ENV 
          echo "CODY_COMMIT=${{ github.event.inputs.cody-commit || LATEST_COMMIT }}" >> $GITHUB_ENV
          echo "JB_VERSION=$(git describe --tags)" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$JB_VERSION-$CODY_COMMIT" >> $GITHUB_ENV
      - run: echo "Publishing version $RELEASE_VERSION"
      - run: ./gradlew buildPlugin "-PpluginVersion=$RELEASE_VERSION" "-Pcody.commit=$CODY_COMMIT"
      - run: ./gradlew --stop
      - name: Upload the plugin package
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: './build/distributions/Sourcegraph-*.zip'
          compression-level: 0
          retention-days: 3
