name: Release to Marketplace
on:
  push:
    tags: [ "*" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
          cache: "gradle"
      - run: |
          echo "RELEASE_VERSION=$(./scripts/version-from-git-tag.sh)-nightly" >> $GITHUB_ENV
      - run: echo "Publishing version $RELEASE_VERSION"
      - run: ./gradlew "-DpluginVersion=$RELEASE_VERSION" publishPlugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
