name: Release to Marketplace
on:
  push:
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
      - run: echo "RELEASE_VERSION=$(./scripts/version-from-git-tag.sh)-alpha" >> $GITHUB_ENV
      - run: echo "Publishing version $RELEASE_VERSION"
      - run: ./gradle "-DpluginVersion=$RELEASE_VERSION" publishPlugin
