name: JetBrains Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    name: JetBrains tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - run: yarn global add pnpm@9.0.5
      - run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        shell: bash
        id: pnpm-cache
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-${{ matrix.node }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.node }}-pnpm-store-k
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
          cache: gradle
      # Skip Code Search build in CI because it's slow, and we don't use it anyway for testing purposes.
      - run: echo "SKIP_CODE_SEARCH_BUILD=true" >> $GITHUB_ENV
      - run: ./gradlew test
      - run: ./gradlew buildPlugin
      - run: ./gradlew spotlessCheck
      - run: ./gradlew --stop
